---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "grababyte/docker-${MOLECULE_OS:-centos}-base:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: false
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
