---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_IMAGE}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
lint: |
  set -e
  ansible-lint .
  yamllint .
scenario:
  name: default
  test_sequence:
    -  lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - destroy
