---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  get-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/getVersion.yml@0.5.3
    with:
      metadataFile: 'main.yml'
      metadataPath: 'meta'
  yaml-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/yamlLint.yml@0.5.3
    with:
      yamlPath: .
    needs: get-version
  molecule-test:
    uses: GrabAByte/github-devops-workflows/.github/workflows/ansibleMolecule.yml@0.5.3
    needs: get-version
  sonar-scan:
    uses: GrabAByte/github-devops-workflows/.github/workflows/sonarScan.yml@0.5.3
    secrets:
      WORKFLOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs: get-version
  update-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/updateVersion.yml@0.5.3
    with:
      gitUsername: 'grababyte'
      gitEmail: 'grababyte@github.com'
      metadataFile: 'main.yml'
      metadataPath: 'meta'
    needs: [yaml-lint, molecule-test, sonar-scan]
  ansible-release:
    uses: GrabAByte/github-devops-workflows/.github/workflows/ansibleRelease.yml@0.5.3
    secrets:
      GALAXY_TOKEN: ${{ secrets.GALAXY_TOKEN }}
    needs: update-version
