---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

env:
  artifact: metadata.sh
  path: metadata

jobs:
  gather-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/uploadMetadata.yml@feat/shareVars
    with:
      artifact: ${{ env.artifact }}
      path: ${{ env.path }}
  read-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/downloadArtifact.yml@feat/shareVars
    with:
      artifact: ${{ env.artifact }}
      path: ${{ env.path }}
  yaml-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/yamlLint.yml@main
    with:
      yamlPath: '.'
