---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  gather-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/uploadMetadata.yml@feat/shareVars
    with:
      artifact: metadata.sh
      path: artifacts
  yaml-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/yamlLint.yml@main
    with:
      yamlPath: '.'
