---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

# workflow_call with env: based parameters is not supported so parameters may be repeated below
jobs:
  write-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/writeMetadata.yml@feat/shareVars
    with:
      inputFile: 'main.yml'
      inputPath: 'meta'
      outputFile: 'metadata.sh'
      outputPath: 'metadata'
  yaml-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/yamlLint.yml@main
    with:
      yamlPath: '.'
    needs: gather-metadata
  read-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/readMetadata.yml@feat/shareVars
    with:
      outputFile: 'metadata.sh'
      outputPath: 'metadata'
    needs: gather-metadata
