---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  gather-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/yamlLint.yml@feat/shareVars
  yaml-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/yamlLint.yml@main
    with:
      yamlPath: '.'
