---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

env:
  artifact: main.yml
  path: meta

jobs:
  gather-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/uploadMetadata.yml@feat/shareVars
    with:
      artifact: main.yml
      path: meta
  read-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/downloadArtifact.yml@feat/shareVars
    with:
      artifact: main.yml
      path: meta
  yaml-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/yamlLint.yml@main
    with:
      yamlPath: '.'
